#! python3
# textMyself.py - Defines the textmyself() function that texts a message 
# passed to it as a string

# Preset values:
accountSID = 'ACxxxxxxxxxx'
authToken = 'xxxxxxxxxxxxx'
myNumber = '+1555999888'
twilioNumber = '+15552225678'

from twilio.rest import TwilioRestClient

def textmyself(message):
	twilioCli = TwilioRestClient(accountSID, authToken)
	twilioCli.messages.create(body=message, from_=twilioNumber, to=myNumber)

